language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- python -m unittest discover
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: Dl/PkR9apQb+gAwFWTo06j6hisRZMj/DxQ1OsOdUOcokHmhij0dtUDU7ChFISqWBgg9KAVvwnGkRNM6x+3+eFnJpfvOmB4EyrgA+eZOK0s9kDQUSaLYL32brIejKa/IF2daGnNDRmEYiAkfPvcrtNHk0CvY3+2mLE5Dy83SlWBkksGLtNt0g0ZhNR1H2pIgVxMnjrMBfXLsjF8iGrE2uvqYVvrqWbh7OAsJgtWiOuIRVPPiZ10vMkwNM4N8OXWq1WtCdRARe+9vZgPoZfNiH0Wye10/ho22KXpNuQ52XXBX3aNd7l+N+Kndx8fLyyppjlnL31EVJuU4AFeDOzS+4Kh2ac1bd+IUA6ByYXxuCHZJs/tf8j0OIsJhpmyJlpPuAixil+FTKa1Bm13ofStq7FLi66e5yJsDUoaTtVkNBOpOZoOELPOYFcCwrzZqHssOKLbyDzlOEUeF71n+Jmi/yWCONb9vdj4n62AoVnRAA2sFEtWi5jI4rIj55d9/wQUBqbZZiS7VknSR4Y7b31Xqo+ctBltrW49gml6EcMCAbOipUt+8kioNc/de/cDER4ZSM1RhG5xUEBMr9eYaEpwJIEFHOe1HvYuyASiRU+VHv9Gc7PjFKluEcHVRFxqKffALd2Ads39jeTIPBRAOdqdbfj7OymkMm/akHDSyFoR2C5bA=
  app: cisc3140test3-api-heroku
