language: python

python:
    - "3.7"
    - "3.6"

# install dependencies
install: 
  - pip install -r requirements/dev.txt
script:
  - python test_app.py

# Deployment to Heroku
branches:
  only:
    - master

deploy:
  - provider: heroku
    api_key: 78832b22-f8e4-44d8-8917-eaf540f2e965
    app: cisc3140hw3